import Head from 'next/head';
import { useEffect, useState, Fragment } from 'react';
import styles from '../styles/Home.module.css';

import Link from 'next/link';

export default function Home() {
	const [users, setUsers] = useState([]);

	useEffect(() => {
		fetch('/api/users')
			.then((res) => res.json())
			.then((data) => setUsers(data));
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h1>Fetch User List from API Routes</h1>

			<ul>
				{/* <li>Aang</li> */}
				{users?.map((user, idx) => (
					<Fragment key={idx}>
						<Link href={`/${user.id}`}>{user.name}</Link>
						<br />
					</Fragment>
				))}
			</ul>
		</div>
	);
}
